galaxy_info:
  author:
    - sawyer.lee@krustuniverse.com
  description: "Klaytn BlockChain Bridge Configuration"
  company: Krust Universe
  license: MIT
  min_ansible_version: 2.4
  galaxy_tags: [blockchain, klay, klaytn, ansible, krustuniverse]

dependencies: []
